name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not "main"
permissions:
        contents: write
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.2' # Use your desired Node version
    - name: Install dependencies
      run: npm ci
      

    - name: Build with API URL
      run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> "$GITHUB_ENV"
          npm run build
      

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
            branch: gh-pages
            folder: build
            token: ${{ secrets.GH_PAT }}  # Use the PAT instead of the default token
        
